tags_to_save = [
 'javascript',
 'linux',
 'php',
 'java',
 'python',
 'программирование',
 'разработка',
 '.net',
 'c++',
 'c#',
 'ubuntu',
 'ruby',
 'web-разработка',
 'api',
 'mysql',
 'c',
 'node.js',
 'веб-разработка',
 'алгоритмы',
 'виртуализация',
 'qt',
 'интерфейсы',
 'sql','машинное обучение', 'ml', 'dl', 'machine learning','docker']


config = dict(
    data_dir="data",
    tags_to_save=tags_to_save,
    train_size=20000,
    class_ratio=0.5,
    model="cointegrated/rubert-tiny2",
    tokenizer="cointegrated/rubert-tiny2",
    batch_size=32,
    is_finetuning=True,
    learning_rate=1e-5,
    epochs=4,
    num_warmup_steps=0,
)
